### ISSUE TITLE
I have installed the plugin, but how to execute the inspection?

### ISSUE THREAD

**Issue by jjvargas** [erikzielke/butterknife_inspections#1]

**Comment by erikzielke** [comment]
They run automatically. You can run them manually via Run Inspection by Name... search for butterknife, then you can select the ones to run. 

The one named Optional but not nullable is not enabled by default.

**Comment by ashish-solankar** [comment]
Hi @erikzielke ,
I installed plugin and restarted, checked in setting enabled Optional but not nullable
Using following version of android studio.
Android Studio 3.5.3

> Build #AI-191.8026.42.35.6010548, built on November 15, 2019
> JRE: 1.8.0_202-release-1483-b03 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

**Im not getting any warnings**. I also tried with run inspection by name.
Recently started using plugins for android studio is there anything else require to enable inspection? am i missing something ?
Thanks,
Ashish Solankar.

**Comment by erikzielke** [comment]
Hi @ashish-solankar .

I haven't maintained this plugin for a very long time, so doubt it works anymore. So should probably just remove it from the plugin repository.

By the way as far as I understand to use butterknife is deprecated - and should use e.g. viewbinding instead (see https://github.com/JakeWharton/butterknife)
